### ISSUE TITLE
Can't setup php-language-server

### ISSUE THREAD

**Issue by bodqhrohro** [natebosch/vim-lsc#69]
In `.vimrc`:
`let g:lsc_server_commands = {'python': 'pyls', 'php': 'php /home/bodqhrohro/.composer/vendor/felixfbecker/language-server/bin/php-language-server.php'}`

When I open a PHP file in Vim 8.0, I get a message:
```
LSC Error!: TypeError: Argument 2 passed to LanguageServer\LanguageServer::initialize() must be of the type string, integer given, called in /home/bodqhrohro/.composer
/vendor/felixfbecker/advanced-json-rpc/lib/Dispatcher.php on line 164 and defined in /home/bodqhrohro/.composer/vendor/felixfbecker/language-server/src/LanguageServer.
php:168
Stack trace:
#0 /home/bodqhrohro/.composer/vendor/felixfbecker/advanced-json-rpc/lib/Dispatcher.php(164): LanguageServer\LanguageServer->initialize(Object(La
nguageServer\Protocol\ClientCapabilities), 9726)
#1 /home/bodqhrohro/.composer/vendor/felixfbecker/language-server/src/LanguageServer.php(131): AdvancedJsonRpc\Dispat
cher->dispatch(Object(AdvancedJsonRpc\Request))
#2 [internal function]: LanguageServer\LanguageServer->LanguageServer\{closure}()
#3 /home/bodqhrohro/.composer/vendo
r/sabre/event/lib/coroutine.php(64): Generator->valid()
#4 /home/bodqhrohro/.composer/vendor/sabre/event/lib/coroutine.php(118): Sabre\Event\{closure}()
#5 /home/bod
qhrohro/.composer/vendor/felixfbecker/language-server/src/LanguageServer.php(154): Sabre\Event\coroutine(Object(Closure))
#6 /home/bodqhrohro/.composer/vendor/sabre/e
vent/lib/EmitterTrait.php(88): LanguageServer\LanguageServer->LanguageServer\{closure}(Object(LanguageServer\Protocol\Message))
#7 /home/bodqhrohro/.composer/vendor/f
elixfbecker/language-server/src/ProtocolStreamReader.php(56): Sabre\Event\Emitter->emit('message', Array)
#8 /home/bodqhrohro/.composer/vendor/sabre/event/lib/Loop/Lo
op.php(311): LanguageServer\ProtocolStreamReader->LanguageServer\{closure}()
#9 /home/bodqhrohro/.composer/vendor/sabre/event/lib/Loop/Loop.php(233): Sabre\Event\Loop
\Loop->runStreams(NULL)
#10 /home/bodqhrohro/.composer/vendor/sabre/event/lib/Loop/Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#11 /home/bodqhrohro/.composer/ve
ndor/sabre/event/lib/Loop/functions.php(122): Sabre\Event\Loop\Loop->run()
#12 /home/bodqhrohro/.composer/vendor/felixfbecker/language-server/bin/php-language-server.
php(102): Sabre\Event\Loop\run()
```
And server is not started.

**Comment by natebosch** [comment]
https://github.com/felixfbecker/php-language-server/blob/6894d85aaf2907d72db443f1a8b0a8d52f640900/src/LanguageServer.php#L168

Looks like the `rootPath` argument is not set correctly. I'm not super familiar with php - but there is some magic happening with how these arguments are getting assigned:
https://github.com/felixfbecker/php-advanced-json-rpc/blob/8c2d25c45f05ae43790f585047e1191c558d86c6/lib/Dispatcher.php#L164

Two possibilities I can think of:
- there is a bug in that code which is assigning the `pid` argument where the `rootPath` should go. (maybe it doesn't expect the `trace` argument and that throws it off?)
- we're somehow assigning an integer value to the `rootPath` on the client side.

You could try removing the `trace` argument with a `message_hook` and see if that unblocks it.

```viml

function! DropTraceParam(method, params) abort
  unlet a:params.trace
  return a:params
endfunction

let g:lsc_server_commands = {
    \ 'python': 'pyls',
    \ 'php': {
    \    'name': 'php-language-server',
    \    'command': 'php /home/bodqhrohro/.composer/vendor/felixfbecker/language-server/bin/php-language-server.php',
    \    'messag_hooks': { 'initialize': function('DropTraceParam') },
    \  }
    \}
```

**Comment by armivit** [comment]
Type error in `'messag_hooks'` property but with `'message_hooks'` also does not work for me.
```
Error detected while processing function <SNR>19_OnOpen[4]..lsc#file#onOpen[1]..lsc#server#start[3]..<SNR>34_Start[42]..lsc#server#call[6]..lsc#config#messageHook:
line    4:
E704: Funcref variable name must start with a capital: hook
```

**Comment by natebosch** [comment]
@armivit - the Funcref variable name should be fixed by https://github.com/natebosch/vim-lsc/commit/8a94bd845c30ef596ef220a352bc61e3aaa975cb

Can you update and try again?

**Comment by armivit** [comment]
Hook works! But it does not solve the problem.
After several tests I have found a solution:
```
function! DropTraceParam(method, params) abort
    unlet a:params.trace
    let a:params.rootPath = a:params.rootUri
    return a:params
endfunction
```
But now I have another problem with file paths.
```
LSC Error!: ErrorException: file_get_contents(file:\\\home\my\project\composer.json): failed to open stream: No such file or directory ...
```
I see reverse slashes (Windows-style) but request params were correct:
```
{'rootUri': 'file:///home/my/project', 'capabilities': {'workspace': {'applyEdit': v:false}, 'textDocument': {'completion': {'snippetSupport': v:false}, 'synchronization': {'willSaveWaitUntil': v:false, 'willSave
': v:false, 'didSave': v:false}, 'definition': {'dynamicRegistration': v:false}}}, 'rootPath': 'file:///home/my/project', 'processId': 8648}
```
File `/home/my/project/composer.json` exists of course and `php -r "file_get_contents('file:///home/my/project/composer.json');"` works without an error.

**Comment by natebosch** [comment]
`rootPath` is an old parameter that was replaced by `rootUri` - perhaps the PHP language server hasn't been updated with new versions of the spec?

I think if you're setting that parameter you probably don't want to use the `rootUri` value directly - you likely want to strip the `file://` since `rootPath` wasn't a URI.

You might be able to get things into a working state, but I suspect it won't be easy if the client and server aren't expecting the same version of the spec. I'd recommend filing issues against the server to see if it can be updated to support the latest spec.

**Comment by armivit** [comment]
@natebosch thank you!

I found rootUri parameter in "multi-root" branch of felixfbecker/language-server and [it looks](https://github.com/felixfbecker/php-language-server/blob/8741e287adb53447f449b5ca1487cc14dc0b335a/src/LanguageServer.php#L170) very similar [the spec](https://github.com/Microsoft/language-server-protocol/blob/gh-pages/specification.md#initialize-request-leftwards_arrow_with_hook).

Installing:
```
composer config minimum-stability dev && composer require felixfbecker/language-server:dev-multi-root
```

Initialize hook (I don't know why server does not work without definition all optional parameters):
```
function! DropTraceParam(method, params) abort
    let a:params.rootPath = v:none
    let a:params.workspaceFolders = v:none
    return a:params
endfunction
```

Server branch is unstable but it works.

**Comment by natebosch** [comment]
I think we've determined the bugs are on the server side and it sounds like the workaround is to use the latest branch and a message hook to specify the parameters that are not required by the spec but are required by this server. Will close for now.
